apiVersion: 1

datasources:
  - name: rpc-de-01
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.4:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: rpc-de-02
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.6:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: rpc-fi-01
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.5:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: rpc-fi-01
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.5:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: pokt-fr-1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.10:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: pokt-lt-1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.3:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: harmony-fr-1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.11:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: moonbeam-lt-01
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.13.13.2:9090
    basicAuth: false
    isDefault: false
    editable: true